### ISSUE TITLE
`DKF_DEAD` flag in `DEADKEY.uFlags`

### ISSUE THREAD

**Issue by DJm00n** [lelegard/winkbdlayouts#1]
>The last field of each entry in dead_keys is a mask of flags. The only defined flag is DKF_DEAD, unused in all standard keyboards, with unclear usage.

`DKF_DEAD` flag is used for a dead key chaining. See http://archives.miloush.net/michkap/archive/2011/04/16/10154700.html and http://www.kbdedit.com/manual/dead_chained.html

**Comment by lelegard** [comment]
Hi @DJm00n 

Thanks you for the additional information. It is clear now.

**Comment by lelegard** [comment]
@DJm00n, I have added your remark in the README.md file.
Thanks again
