### ISSUE TITLE
Explanation, why the keys @/# and </> are sometimes inverted on Mac.

### ISSUE THREAD

**Issue by eugenegff** [lelegard/winkbdlayouts#2]
Explanation, why the keys @/# and </> are sometimes inverted on Mac.

0. There exists at least two physical keyboard types, US style ANSI without extra key between left Shift and Z and ISO with such extra key. 

1. Long time ago Apple assigned different scancodes to some keys for ANSI and ISO Apple Desktop Bus (ADB) keyboards, effectively moving key with ADB scancode 32 from the location below Esc on ANSI keyboards to the location near left Shift on ISO keyboards, and assigning new scancode 0A to the key below Esc on ISO keyboard. It was done in hardware, by physically rerouting wires, so for example symbol "~" was always assigned by US keyboard layout to scancode 32, and was located below Esc for ANSI and near the Shift for ISO ADB keyboards. Other languages assigned other symbols to the key with scancode 32, physical location of those symbols moved between ANSI and ISO ADB keyboards the same way.

![LD8pT](https://github.com/lelegard/winkbdlayouts/assets/34012295/bc0ce70b-f2bf-4aef-b672-c144391bb8a9)

2. For the backward compatibility purposes ADB scancodes are used even on modern versions of macOS, with PS/2, USB or Bluetooth keyboard drivers translating native scancodes to ADB scancodes very early. Behavior of "moving" key with ADB scancode 32 is emulated inside driver if macOS autodetects or if user specified that ISO style keyboard is in use.

3. Most of VM software were written by US programmers that are not aware about this "jumping" key 32, but Parallels Desktop developers were aware, and compensated "jumping" key 32 so that key under the Esc has stable IBM Set2 scancode inside VM no matter was it ANSI or ISO keyboard from macOS host point of view.

4. But Parallels Desktop developers attempted to create windows layouts that match macOS native keyboard layouts, and after providing stable IBM Set2 scancodes inside VM they were not able to emulate "jumping" behavior for "~" key inside VM, that was still occurs inside macOS host!

Therefore, having "alternative" keyboard layout with swapped keys with ADB scancodes 32 and 0F or equivalently IBM scancodes 29 and 56 is useful not only on VmWare, but even on Parallels Desktop, especially for situations when Windows keyboard layout created from European macOS keyboard layout is used on Mac with ANSI keyboard.

**Comment by eugenegff** [comment]
Right now I have a problem with macOS PL keyboard layout assigning " ~ " to ADB key 32 that should have been near the Shift as Polish language usually uses ISO style keyboards. Parallels Desktop "mirror" PL keyboard layout assigned " ~ " to VK_OEM_102 that is assigned to the key with IBM scancode 56 physically absent on my MacBook that have ANSI style keyboard. At the same time in macOS ADB key 32 is always present, and is physically located below Esc on my MacBook with ANSI style keyboard.

**Comment by lelegard** [comment]
Thanks @eugenegff for the explanations.

I directly jumped from my Apple II in the early 80's to an iMac in 2015. I the meantime, I only used various Unix workstations and Windows PC. This is why I missed all the intermediate story.

**Comment by lelegard** [comment]
@eugenegff, I have added a reference to your explanation in the README file.
