### ISSUE TITLE
about hotkeys and modifiers...

### ISSUE THREAD

**Issue by neuromagus** [lelegard/winkbdlayouts#7]
hello, guys. 
Thanks a lot for this best tools pack. These programs helped me a lot to understand complex things (bitmask) for creating best layout ever ;) (Windows Driver Kit or this package). But this topic is vast and my knowledge is not deep yet... 

So, I have a couple of questions.
Firstly, I created a layer with modificator 'Kana':

```
// in scancode replace RCTRL to KANA (VK_OEM_8)
// After fix a bitmask

static VK_TO_BIT vk_to_bits[] = {
    {VK_SHIFT,   KBDSHIFT},
    {VK_CONTROL, KBDCTRL},
    {VK_MENU,    KBDALT},
    {VK_OEM_8,   KBDKANA},
    {0,          0}
};

static MODIFIERS char_modifiers = {
    .pVkToBit    = vk_to_bits,
    .wMaxModBits = 8,
    .ModNumber   = {
        0,            // 000 = <none>
        1,            // 001 = Shift
        // disable another modification
        SHFT_INVALID, // 010 = Control
        SHFT_INVALID, // 011 = Shift Control
        SHFT_INVALID, // 100 = Alt
        SHFT_INVALID, // 101 = Shift Alt
        SHFT_INVALID, // 110 = Control Alt (AltGr)
        SHFT_INVALID, // 111 = Shift Control Alt (Shift AltGr)
        2, // this is my best modificator for new layer.
    }
};

// and add new layer
static VK_TO_WCHARS3 vk_to_wchar3[] = {
    //                     Base   Shift  Kana
    //                     ----   ----- ------
    ....
    {'A',          CAPLOK, {L'a', L'A', L'0'}},
    {'D',          CAPLOK, {L'd', L'D', L'2'}},
    {'F',          CAPLOK, {L'f', L'F', L'3'}},
    {'J',          CAPLOK, {L'j', L'J', L'('}},
    {'K',          CAPLOK, {L'k', L'K', L')'}},
    {'M',          CAPLOK, {L'm', L'M', L'['}},
    {'S',          CAPLOK, {L's', L'S', L'1'}},
    {VK_OEM_COMMA, 0x00,   {L',', L'<', L']'}},
    ....
    {0,            0,      0,     0,    0}
};
```

All works fine, but... what to do with hotkeys that require characters through a modifier?
I want use hotkey, for example, "ctrl+1", need press kana+ctrl+S in this case, and nothing happend. Why?

The second question follows from the first, for correct work hotkeys this record is not valid?
```
{'A',          CAPLOK, {L'b', L'B', L'№'}},
```
Need change scancode on position 'A' to scancode 'b'?
If you have time to answer, I would be grateful.

P.S. Sorry for my terrible English.

**Comment by DJm00n** [comment]
Hotkeys are working based on VK keys, not chars. VK keys are coming in `WM_KEYDOWN`/`WM_KEYUP` events in Win32 applications. Characters are coming in `WM_CHAR` events in Win32 applications.

So in your case you'll have `VK_OEM_8` + `VK_SHIFT` + `VK_S` in three `WM_KEYDOWN` messages when pressing Kana+Ctrl+S. And then `1` in one `WM_CHAR` message.
